export const SOCKET = {
  ENDPOINT: {
    SUBSCRIBE: '/sub',
    PUBLICATION: '/pub',
  },
  ROOMS: '/rooms',
  ENTER: '/enter',
  EXIT: '/exit',
  CHAT: '/chat',
  READY: '/ready',
  UNREADY: '/unready',
  CHANGE_GAME: '/change-game',
  CHANGE_PLAYER_NAME: '/change-player-name',
  BG_START: '/balance-game/start',
  BG_SELECT_A: '/balance-game/select-a',
  BG_SELECT_B: '/balance-game/select-b',
  BG_UNSELECT: '/balance-game/unselect',
  BG_NEXT: '/balance-game/next',
  BG_END: '/balance-game/end',
  TYPE: {
    ENTER: 'ENTER',
    EXIT: 'EXIT',
    CHAT: 'CHAT',
    READY: 'READY',
    UNREADY: 'UNREADY',
    CHANGE_GAME: 'CHANGE_GAME',
    CHANGE_PLAYER_NAME: 'CHANGE_PLAYER_NAME',
    BG_START: 'BG_START',
    BG_SELECT: 'BG_SELECT',
    BG_UNSELECT: 'BG_UNSELECT',
    BG_NEXT: 'BG_NEXT',
    BG_END: 'BG_END',
  },
};
