export const SOCKET = {
  ENDPOINT: {
    SUBSCRIBE: '/topic',
    PUBLICATION: '/app',
    USER: {
      QUEUE_ERRORS: '/user/queue/errors',
    },
    ROOM: {
      ROOMS: '/rooms',
      ENTER: '/rooms/enter',
      EXIT: '/rooms/exit',
      CHAT: '/rooms/chat',
      READY: '/rooms/ready',
      UNREADY: '/rooms/unready',
      CHANGE_GAME: '/rooms/change-game',
      CHANGE_PLAYER_NAME: '/rooms/change-player-name',
    },
    BALANCE_GAME: {
      START: '/games/balance-game/start',
      SELECT_A: '/games/balance-game/select-a',
      SELECT_B: '/games/balance-game/select-b',
      UNSELECT: '/games/balance-game/unselect',
      NEXT: '/games/balance-game/next',
      END: '/games/balance-game/end',
    },
    QNA_GAME: {
      START: '/games/qna-game/start',
      SUBMIT: '/games/qna-game/submit',
      LIKE: '/games/qna-game/like',
      UNLIKE: '/games/qna-game/unlike',
      NEXT: '/games/qna-game/next',
      END: '/games/qna-game/end',
    },
  },
  TYPE: {
    ROOM: {
      ENTER: 'ENTER',
      EXIT: 'EXIT',
      CHAT: 'CHAT',
      READY: 'READY',
      UNREADY: 'UNREADY',
      CHANGE_GAME: 'CHANGE_GAME',
      CHANGE_PLAYER_NAME: 'CHANGE_PLAYER_NAME',
      ERROR: 'ERROR',
    },
    BALANCE_GAME: {
      START: 'BG_START',
      SELECT: 'BG_SELECT',
      UNSELECT: 'BG_UNSELECT',
      NEXT: 'BG_NEXT',
      ALL_RESULTS: 'BG_ALL_RESULTS',
      END: 'BG_END',
    },
    QNA_GAME: {
      START: 'QNA_START',
      SUBMIT: 'QNA_SUBMIT',
      LIKE: 'QNA_LIKE',
      UNLIKE: 'QNA_UNLIKE',
      NEXT: 'QNA_NEXT',
      ALL_RESULTS: 'QNA_ALL_RESULTS',
      END: 'QNA_END',
    },
  },
  SYSTEM: 'system',
};
