name: Push To Dev Repo

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      # 부모 레포지토리에서만 실행되도록 설정
      - name: Check repository
        if: github.repository == 'Team-groupHi/grouphi-mvp-fe'
        uses: actions/checkout@v4

      - name: Install mustache (to update the date)
        if: github.repository == 'Team-groupHi/grouphi-mvp-fe'
        run: apk add ruby && gem install mustache

      - name: creates output
        if: github.repository == 'Team-groupHi/grouphi-mvp-fe'
        run: sh ./build.sh

      - name: Pushes to dev deploy repository
        if: github.ref == 'refs/heads/dev' && github.repository == 'Team-groupHi/grouphi-mvp-fe'
        id: push_dev_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEV_ACCESS_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: SoJuSo
          destination-repository-name: grouphi-mvp-fe
          user-email: 'asdfg7123@gmail.com'
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: dev

      - name: Test get variable exported by push-to-another-repository
        if: github.repository == 'Team-groupHi/grouphi-mvp-fe'
        run: echo $DESTINATION_CLONED_DIRECTORY
